version: "0.0.1"
services:
  backend:
    image: back-end-api
    build:
      context: ./go-back-end
    ports:
      - "8080:8080"
  frontend:
    image: front-end-api
    build:
      context: ./next-front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend
